### ISSUE TITLE
Error: Cannot find module './event'

### ISSUE THREAD

**Issue by akazakou** [sinonjs/nise#27]
After an update up to 1.2.1 version I found that error message:

```log
Error: Cannot find module './event'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kantora.pro/node-backend-skeleton/node_modules/.registry.npmjs.org/nise/1.2.1/node_modules/nise/lib/event/index.js:4:12)
```

Believe that happens because directory `lib/event` doesn't contain 'event.js' module

**Comment by akazakou** [comment]
Looks like package in NPM repository contains broken build https://registry.npmjs.org/nise/-/nise-1.2.1.tgz

**Comment by Flarna** [comment]
see #26

**Comment by hacdias** [comment]
Same here.

**Comment by andreylushchick-planorama** [comment]
+1, we're experiencing same issue

**Comment by bajzarpa** [comment]
+1

**Comment by szll** [comment]
+1

**Comment by JonJagger** [comment]
+1, me too. In a Dockerfile I have
RUN npm install -global mocha chai sinon sinon-chai
and the diagnostic you get is
npm WARN deprecated nise@1.2.1: This version misses certain files. See #26

**Comment by f-roland** [comment]
+1 to remove this version from the registry and put an end to broken builds without having to patch our code to manually require this lib with the correct version

**Comment by afzalSH** [comment]
facing same issue!

**Comment by mroderick** [comment]
I am looking into this

**Comment by 3LOK** [comment]
Ahhh!!!! +1.... fast!

**Comment by f-roland** [comment]
@mroderick can you please remove the version from npm in the meantime ?
the deprecation message doesn't stop builds to break 🤕

**Comment by afzalSH** [comment]
+1

**Comment by gmukul01** [comment]
+1 I am using sinon for unit testing in react. And as sinon uses this package internally i also got the same issue.
 Cannot find module './event' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-runner/node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/nise/lib/event/index.js:4:12)

**Comment by mroderick** [comment]
I have unpublished `nise@1.2.1` as that was clearly not a good build. That should fix the issue for everyone.

This was caused by #26, which I merged this morning. I am investigating how to make a good build, and will publish `nise@1.2.2` later.

**Comment by JonJagger** [comment]
Yup that's fixed it for me. Thanks

**Comment by cdouine39** [comment]
@mroderick thanks for being so reactive !! :)

**Comment by 7etrahedral** [comment]
thumbs up.

**Comment by mroderick** [comment]
@fatso83 has already fixed it by publishing `sinon@1.2.2` 👍

**Comment by mroderick** [comment]
This has been fixed with https://github.com/sinonjs/nise/commit/5dd5b007036d092a44b120bcb003f665f042a2ee
